services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      YOUTUBE_APIKEY_1: ${YOUTUBE_APIKEY_1}
      YOUTUBE_APIKEY_2: ${YOUTUBE_APIKEY_2}
      YOUTUBE_APIKEY_3: ${YOUTUBE_APIKEY_3}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    ports:
      - "9000:9000"
    depends_on:
      postgres-db:
        condition: service_healthy

  cron:
    container_name: cron
    build:
      context: ./cron
      dockerfile: Dockerfile
    environment:
      YOUTUBE_APIKEY_1: ${YOUTUBE_APIKEY_1}
      YOUTUBE_APIKEY_2: ${YOUTUBE_APIKEY_2}
      YOUTUBE_APIKEY_3: ${YOUTUBE_APIKEY_3}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    depends_on:
      - backend

  postgres-db:
    container_name: postgres-db
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}'"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./backend/database/pgdata:/var/lib/postgresql/data
      - ./scripts/init.sh:/docker-entrypoint-initdb.d/init.sh